---
kind: pipeline
name: default

clone:
  depth: 1

steps:
  - name: vet
    image: golang:1.12
    volumes:
      - name: gopath
        path: /go
    commands:
      - go vet ./...

  - name: test
    image: golang:1.12
    volumes:
      - name: gopath
        path: /go
    commands:
      - go test -cover ./...

  - name: release
    image: golang:1.12
    volumes:
      - name: gopath
        path: /go
    commands:
      - go get github.com/mitchellh/gox
      - go get github.com/tcnksm/ghr
      - gox -output "dist/synchub_{{.OS}}_{{.Arch}}"
      - ls dist/

volumes:
  - name: gopath
    temp: {}

trigger:
  event:
    - push
